version: '3.3'

services:
  tigris:
    container_name: tigris-local-server
    image: tigrisdata/tigris-local
    ports:
      - "8081:8081"

  service:
    container_name: tigris_test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BRANCH
    environment:
      - TIGRIS_URL
      - TIGRIS_CLIENT_ID
      - TIGRIS_CLIENT_SECRET
    ports:
      - "8080:8080"
    depends_on:
      - tigris
