# https://taskfile.dev

version: '3'

env:
  BRANCH:
    sh: git branch --show-current

dotenv: [ '.env' ]

tasks:
  default:
    cmds:
      - task -l
    silent: true

  # Start local Tigris instance if TIGRIS_URL in the .env points to the localhost
  ensure:tigris:
    status:
      - bin/tigris ping || echo "$TIGRIS_URL" | grep -v "localhost"
    cmds:
      - bin/tigris local up --create-project test --create-branch $BRANCH

  run:
    desc: Start the project
    deps: [deps]
    cmds:
      - task: ensure:tigris
      - bin/tigris branch reset $BRANCH
      - go run -ldflags "-X 'main.Branch={{.BRANCH}}'" main.go

  run:docker:
    desc: Start the project in the docker
    deps: [deps]
    cmds:
      - task: ensure:tigris
      - bin/tigris branch reset $BRANCH
      - TIGRIS_URL={{if eq .TIGRIS_URL "localhost:8081"}}tigris-local-server:8081{{else}}{{.TIGRIS_URL}}{{end}} docker compose up --build -d service
      - echo "The test service is up and running at http://localhost:8080"

  test:
    desc: Run the tests
    deps: [run:docker]
    cmds:
      - go test ./...

  deps:
    desc: Install dependencies
    status:
      - test -x bin/tigris
    cmds:
      - mkdir -p bin
      - curl -sSL https://tigris.dev/cli-{{if eq OS "darwin"}}macos{{else}}{{OS}}{{end}}{{if eq ARCH "arm"}}-arm64{{end}} | tar -xz -C ./bin
      - git config core.hooksPath ./.gitconfig/hooks

  clean:
    desc: Cleanup the resources
    cmds:
      - docker compose down
